[package]
name = "hello_idc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
axum = "0.6.18"
clap = { version = "4.3.23", features = ["derive", "env"]}
maud = { version = "0.25.0", features = ["axum"] }
once_cell = "1.18.0"
openidconnect = "3.3.0"
opentelemetry = { version = "0.20.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.13.0", features = ["grpc-tonic", "http-proto"] }
opentelemetry-semantic-conventions = "0.12.0"
opentelemetry_sdk = "0.20.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.32.0", features = ["full"]}
toml = "0.7.6"
tonic = { version = "0.9.2", features = ["tls", "tls-roots"] }
tower-cookies = { version = "0.9.0", features = ["signed", "private"]}
tower-http = { version = "0.4.3", features = ["tracing", "trace"] }
tracing = "0.1.37"
tracing-opentelemetry = "0.20.0"
tracing-subscriber = { version = "0.3.17", features = ["fmt", "json", "env-filter", "std", "registry"] }
url = "2.4.0"
